"""Smart playlist generation service.

Generates and manages Navidrome Smart Playlist (.nsp) files based on
library content, including:

Key Functions:
    - sanitize_playlist_name(): Strip unsafe characters from names.
    - create_nsp_file(): Write playlist JSON data to disk.
    - create_or_update_playlist_for_artist(): Generate an "Essential"
      playlist for a specific artist.
    - refresh_all_playlists_from_db(): Rebuild all playlists from current
      database ratings.

Architecture:
    Reads tracks with high ratings (>= 4) from the database and generates
    ``.nsp`` files that Navidrome auto-loads from its Playlists directory.
"""
from __future__ import annotations
import json
import os
import re
from sqlalchemy import text
from db.engine import db_session


def sanitize_playlist_name(name: str) -> str:
    return "".join(c for c in name if c.isalnum() or c in ("-", "_", " ")).strip()


def playlist_path(playlist_name: str) -> str:
    music_folder = os.environ.get("MUSIC_FOLDER", "/music")
    playlists_dir = os.path.join(music_folder, "Playlists")
    os.makedirs(playlists_dir, exist_ok=True)
    return os.path.join(playlists_dir, f"{sanitize_playlist_name(playlist_name)}.nsp")


def delete_nsp_file(playlist_name: str) -> None:
    path = playlist_path(playlist_name)
    if os.path.exists(path):
        os.remove(path)


def create_nsp_file(playlist_name: str, playlist_data: dict) -> bool:
    try:
        with open(playlist_path(playlist_name), "w", encoding="utf-8") as handle:
            json.dump(playlist_data, handle, indent=2)
        return True
    except Exception:
        return False


def create_or_update_playlist_for_artist(artist_name: str, tracks: list):
    playlist_name = f"{artist_name} (Essential Playlist)"
    data = {"name": playlist_name, "comment": "Generated by Popularr", "rules": {"artist": artist_name}, "tracks": tracks or []}
    return create_nsp_file(playlist_name, data)


def refresh_all_playlists_from_db():
    with db_session() as session:
        result = session.execute(text("SELECT DISTINCT COALESCE(NULLIF(album_artist, ''), artist) AS artist FROM tracks WHERE rating >= 4"))
        artists = [str(row[0]) for row in result.fetchall() or [] if row[0]]
        count = 0
        for artist in artists:
            result = session.execute(text("SELECT id, title, rating FROM tracks WHERE COALESCE(NULLIF(album_artist, ''), artist) = :artist AND rating >= 4"), {"artist": artist})
            tracks = [{"id": str(row[0]), "title": str(row[1]), "rating": int(row[2])} for row in result.fetchall() or []]
            if create_or_update_playlist_for_artist(artist, tracks):
                count += 1
        return count
