name: opencode

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  opencode:
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && (
        contains(github.event.comment.body, '/oc') ||
        contains(github.event.comment.body, '/opencode')
      )) ||
      (github.event_name == 'pull_request_review_comment' && (
        contains(github.event.comment.body, '/oc') ||
        contains(github.event.comment.body, '/opencode')
      ))

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Configure Git author
        run: |
          git config --global user.name "opencode-agent"
          git config --global user.email "opencode-agent@users.noreply.github.com"

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          model: deepseek/deepseek-v4-flash
          use_github_token: true
